def format_ass_timestamp(seconds: float) -> str:
    """
    Converts seconds into ASS format: h:mm:ss.cs (centiseconds).
    E.g. 1.25 -> 0:00:01.25
    """
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centiseconds = int(round((seconds % 1) * 100))
    if centiseconds >= 100:
        centiseconds = 99
    return f"{hours}:{minutes:02}:{secs:02}.{centiseconds:02}"


def hex_to_ass_color(hex_color: str, alpha_opacity: float = 1.0) -> str:
    """
    Converts standard CSS HEX color (#RRGGBB or RRGGBB) and opacity (0.0 to 1.0)
    into ASS hexadecimal format: &H[AlphaHex][BB][GG][RR]
    Note: ASS Alpha is inverted (00 = fully opaque, FF = fully transparent).
    """
    if not hex_color:
        return "&H00FFFFFF"

    hex_color = hex_color.lstrip('#')
    
    if len(hex_color) == 6:
        r, g, b = hex_color[0:2], hex_color[2:4], hex_color[4:6]
    elif len(hex_color) == 8:
        r, g, b, a = hex_color[0:2], hex_color[2:4], hex_color[4:6], hex_color[6:8]
        # Overwrite alpha_opacity with hex alpha value
        alpha_opacity = int(a, 16) / 255.0
    else:
        return "&H00FFFFFF"

    # Inverted alpha calculation
    alpha_int = int((1.0 - alpha_opacity) * 255)
    alpha_int = max(0, min(255, alpha_int))
    alpha_hex = f"{alpha_int:02X}"

    return f"&H{alpha_hex}{b}{g}{r}"


def generate_ass(segments: list, style: dict) -> str:
    """
    Generates ASS subtitle content from whisper segments and custom style options.
    """
    font_name = style.get("font_name", "Arial")
    font_size = style.get("font_size", 28)
    text_color = style.get("text_color", "#FFFFFF")
    bold = -1 if style.get("bold", False) else 0  # In ASS, -1 is bold, 0 is normal
    italic = -1 if style.get("italic", False) else 0  # In ASS, -1 is italic, 0 is normal
    border_style = style.get("border_style", 1)  # 1 = Outline+Shadow, 3 = Background Box
    outline_color = style.get("outline_color", "#000000")
    outline_width = style.get("outline_width", 2.0)
    back_color = style.get("background_color", "#000000")
    back_opacity = style.get("background_opacity", 0.5)
    shadow = style.get("shadow", 1.0)
    letter_spacing = style.get("letter_spacing", 0.0)
    alignment = style.get("alignment", 2)
    margin_v = style.get("margin_v", 50)  # Standard MarginV in pixels (relative to PlayResY=1080)

    # Convert color formats
    primary_color_ass = hex_to_ass_color(text_color)
    outline_color_ass = hex_to_ass_color(outline_color)
    # Background color with custom opacity
    back_color_ass = hex_to_ass_color(back_color, back_opacity)

    ass_lines = [
        "[Script Info]",
        "; Script generated by AutoSub Premium Subtitle Styling Studio",
        "ScriptType: v4.00+",
        "PlayResX: 1920",
        "PlayResY: 1080",
        "Timer: 100.0000",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        f"Style: CustomStyle,{font_name},{font_size},{primary_color_ass},&H0000FFFF,{outline_color_ass},{back_color_ass},{bold},{italic},0,0,100,100,{letter_spacing},0,{border_style},{outline_width},{shadow},{alignment},50,50,{margin_v},1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
    ]

    for segment in segments:
        # Handle dict or object representation
        if isinstance(segment, dict):
            start = segment.get("start", 0.0)
            end = segment.get("end", 0.0)
            text = segment.get("text", "").strip()
        else:
            start = getattr(segment, "start", 0.0)
            end = getattr(segment, "end", 0.0)
            text = getattr(segment, "text", "").strip()

        # format timestamps
        start_str = format_ass_timestamp(start)
        end_str = format_ass_timestamp(end)

        # Escape newlines for ASS (replace literal newlines with \N)
        text_escaped = text.replace("\n", "\\N").replace("\r", "")

        dialogue_line = f"Dialogue: 0,{start_str},{end_str},CustomStyle,,0,0,0,,{text_escaped}"
        ass_lines.append(dialogue_line)

    return "\n".join(ass_lines)
