"""
Premium ASS Subtitle Generator for AutoSub
Generates Advanced SubStation Alpha files with full styling support
"""

from typing import List, Dict, Optional, Union
from schemas.subtitle_style_schema import SubtitleStyle


def format_ass_timestamp(seconds: float) -> str:
    """
    Converts seconds into ASS format: h:mm:ss.cs (centiseconds).
    E.g. 1.25 -> 0:00:01.25
    """
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centiseconds = int(round((seconds % 1) * 100))
    if centiseconds >= 100:
        centiseconds = 99
    return f"{hours}:{minutes:02}:{secs:02}.{centiseconds:02}"


def hex_to_ass_color(hex_color: str, alpha_opacity: float = 1.0) -> str:
    """
    Converts standard HEX color (RRGGBB or BBGGRR format) to ASS format.
    Handles opacity (0.0 = transparent, 1.0 = opaque).
    ASS format: &H[AlphaHex][BB][GG][RR]
    Note: ASS Alpha is inverted (00 = opaque, FF = transparent)
    """
    if not hex_color:
        return "&H00FFFFFF"

    hex_color = hex_color.lstrip('#')
    
    # Detect if it's already in BGR format (from SubtitleStyle)
    if len(hex_color) == 6:
        # Try to determine format - assume it's already BBGGRR if coming from schema
        # Otherwise convert from RRGGBB
        r, g, b = hex_color[0:2], hex_color[2:4], hex_color[4:6]
        # Standard assumption: BBGGRR from schema
        bgr_format = hex_color
    else:
        return "&H00FFFFFF"

    # Inverted alpha calculation (1.0 opacity = 0x00 alpha, 0.0 opacity = 0xFF alpha)
    alpha_int = int((1.0 - alpha_opacity) * 255)
    alpha_int = max(0, min(255, alpha_int))
    alpha_hex = f"{alpha_int:02X}"

    return f"&H{alpha_hex}{bgr_format}&"


def build_ass_style_line(style: SubtitleStyle, style_name: str = "DefaultStyle") -> str:
    """
    Build a complete ASS Style definition line.
    Format: Style: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
    """
    
    # Convert colors (SubtitleStyle already has BBGGRR format)
    primary_color = hex_to_ass_color(style.text_color)
    outline_color = hex_to_ass_color(style.outline_color)
    
    # Background with opacity
    opacity_fraction = (100 - style.background_opacity) / 100.0
    back_color = hex_to_ass_color(style.background_color, opacity_fraction)
    
    # Secondary color (rarely used, set to transparent yellow)
    secondary_color = "&H00FFFFFF&"
    
    # Bold and Italic as -1 or 0
    bold = -1 if style.bold else 0
    italic = -1 if style.italic else 0
    
    # Border style: 1 = outline+shadow, 3 = opaque box
    border_style = int(style.border_style.value)
    
    # Total outline = outline width + shadow depth
    total_outline = style.outline_width + style.shadow_depth
    
    # Alignment (1-9, numpad)
    alignment = int(style.alignment.value)
    
    # Build style line
    style_line = (
        f"Style: {style_name},"
        f"{style.font_name},"
        f"{style.font_size},"
        f"{primary_color},"
        f"{secondary_color},"
        f"{outline_color},"
        f"{back_color},"
        f"{bold},"
        f"{italic},"
        f"0,"  # Underline
        f"0,"  # StrikeOut
        f"100,"  # ScaleX
        f"100,"  # ScaleY
        f"{style.letter_spacing},"  # Spacing
        f"0,"  # Angle
        f"{border_style},"  # BorderStyle
        f"{total_outline},"  # Outline
        f"{style.shadow_depth},"  # Shadow
        f"{alignment},"  # Alignment
        f"{style.margin_l},"  # MarginL
        f"{style.margin_r},"  # MarginR
        f"{style.margin_v},"  # MarginV
        f"1"  # Encoding
    )
    
    return style_line


def generate_ass(
    segments: List[Union[Dict, object]],
    style: Union[SubtitleStyle, Dict],
    title: str = "AutoSub Generated Subtitles"
) -> str:
    """
    Generates complete ASS subtitle content from segments and styling.
    
    Args:
        segments: List of subtitle segments with 'start', 'end', 'text' keys
        style: SubtitleStyle object or dict with styling properties
        title: Title for the subtitle file
        
    Returns:
        Complete ASS file content as string
    """
    
    # Convert dict to SubtitleStyle if needed
    if isinstance(style, dict):
        style = SubtitleStyle(**style)
    
    ass_lines = [
        "[Script Info]",
        "; Script generated by AutoSub Premium Subtitle Styling Studio",
        f"Title: {title}",
        "ScriptType: v4.00+",
        "PlayResX: 1920",
        "PlayResY: 1080",
        "Timer: 100.0000",
        "WrapStyle: 0",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        build_ass_style_line(style, "Default"),
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
    ]

    # Add dialogue lines
    for layer, segment in enumerate(segments):
        # Handle dict or object representation
        if isinstance(segment, dict):
            start = float(segment.get("start", 0.0))
            end = float(segment.get("end", 0.0))
            text = str(segment.get("text", "")).strip()
        else:
            start = float(getattr(segment, "start", 0.0))
            end = float(getattr(segment, "end", 0.0))
            text = str(getattr(segment, "text", "")).strip()

        if not text:
            continue

        # Format timestamps
        start_str = format_ass_timestamp(start)
        end_str = format_ass_timestamp(end)

        # Escape special characters for ASS format
        text_escaped = text.replace("\n", "\\N").replace("\r", "")
        text_escaped = text_escaped.replace("{", "\\{").replace("}", "\\}")

        dialogue_line = f"Dialogue: {layer},{start_str},{end_str},Default,,0,0,0,,{text_escaped}"
        ass_lines.append(dialogue_line)

    return "\n".join(ass_lines)


def generate_ass_file(
    segments: List[Dict],
    style: Union[SubtitleStyle, Dict],
    output_path: str,
    title: str = "AutoSub Generated Subtitles"
) -> str:
    """
    Generate ASS subtitle file and save to disk.
    
    Args:
        segments: List of subtitle segments
        style: SubtitleStyle configuration
        output_path: Path where ASS file will be saved
        title: Title for the file
        
    Returns:
        Path to generated file
    """
    content = generate_ass(segments, style, title)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return output_path
